spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

  devtools:
    livereload:
      enabled: false
    restart:
      quiet-period: 1900
      poll-interval: 2000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
