version: "3"

services:
  btc-node:
    image: kylemanna/bitcoind@sha256:2d24b29532ecbd4706358ce49b0549b73b905414e62cb2cb7ce431796941344f
    volumes:
      - coin-town-btc-chain-volume:/bitcoin/.bitcoin
    ports:
      - "127.0.0.1:8332:8332"
      - "8333:8333"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command:
      - "-testnet"
      - "-maxmempool=50"
      - "-dbcache=50"
      - "-prune=600"
      - "-disablewallet=0"
      - "-fallbackfee=0.0001"
      - "-server=1"
      - "-rpcbind=0.0.0.0"
      - "-rpcport=8332"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcthreads=1"
      - "-rpcuser=id"
      - "-rpcpassword=pw"
  eth-node:
    image: ethereum/client-go@sha256:b3e4d0d1b36ff73c81aa493176486315a0734cb13f71c67f81a271bc52eb9ac6
    volumes:
      - coin-town-eth-chain-volume:/root
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
      - "30303:30303"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command:
      - "--ropsten"
      - "--syncmode"
      - "light"
      - "--cache"
      - "128"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--ws"
      - "--ws.addr"
      - "0.0.0.0"

volumes:
  coin-town-btc-chain-volume:
  coin-town-eth-chain-volume:
