name: spring-study-1-ci

on:
  push:
    branches:
      - spring-study

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: spring-study-1

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build With Gradle
        run: ./gradlew build
